secrets:
  - key: ANTHROPIC_API_KEY
    description: Claude API key
    required: true
  - key: OPENAI_API_KEY
    description: OpenAI/Codex API key
    required: true
  - key: GOOGLE_API_KEY
    description: Google Gemini API key
    required: false
  - key: TWOCAPTCHA_API_KEY
    description: 2Captcha API key for CAPTCHA solving
    required: false
  - key: REDIS_PASSWORD
    description: Redis password (if enabled)
    required: false
  - key: DB_ENCRYPTION_KEY
    description: Encryption key for SQLite DB
    required: false
  - key: OPERATOR_AUTH_KEY
    description: Operator authorization key for elevated actions
    required: false
  - key: SLACK_WEBHOOK_URL
    description: Slack webhook for alerts
    required: false
  - key: GITHUB_TOKEN
    description: PAT for repo automation (scoped)
    required: false
