name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  claude-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Claude Analysis
        uses: anthropic/claude-action@v1
        with:
          api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            Please review this pull request for:
            - Code quality and best practices
            - Security vulnerabilities
            - Performance implications
            - Architecture consistency
            - Test coverage
          files: ${{ github.event.pull_request.changed_files }}

