name: RTX 4060 GPU Bench

on:
  workflow_dispatch:

jobs:
  bench:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install PyTorch (CUDA 12.4)
        run: |
          python -m pip install --upgrade pip
          pip install --extra-index-url https://download.pytorch.org/whl/cu124 torch torchvision torchaudio
      - name: Run GPU benchmark
        run: |
          python - << 'PY'
import torch, json, time
assert torch.cuda.is_available(), 'CUDA not available'
name = torch.cuda.get_device_name(0)
start = time.time(); torch.cuda.synchronize(); end=time.time()
print(json.dumps({'gpu': name, 'cuda_ok': True}))
PY

